{{- $name := "rabbitmq" -}}
{{- $svc := index .Values "rabbitmq" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
        ports:
        - containerPort: 5672
          name: amqp
        {{- if $svc.service.managementPort }}
        - containerPort: {{ $svc.service.managementPort }}
          name: management
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
            add: ["CHOWN","SETGID","SETUID","DAC_OVERRIDE"]

        resources:
          {{- toYaml $svc.resources | nindent 10 }}  

---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
  - port: {{ $svc.service.port }}
    targetPort: 5672
    name: amqp
  {{- if $svc.service.managementPort }}
  - port: {{ $svc.service.managementPort }}
    targetPort: 15672
    name: management
  {{- end }}
