{{- $name := "front-end" -}}
{{- $svc := index .Values "front-end" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $name }}
spec:
  replicas: {{ $svc.replicas }}
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
      - name: {{ $name }}
        image: "{{ $svc.image.repository }}:{{ $svc.image.tag }}"
        ports:
        - name: http  
          containerPort: {{ $svc.service.containerPort }}
        securityContext:
          readOnlyRootFilesystem: true
          capabilities:
            drop: ["ALL"]
            {{- if $svc.securityContext.capabilities.add }}
            add:
              {{- toYaml $svc.securityContext.capabilities.add | nindent 14 }}
            {{- end }}
        resources:
          {{- toYaml $svc.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ $name }} 
spec:
  selector:
    app: {{ $name }}
  ports:
  - name: http     
    port: {{ $svc.service.port }}
    targetPort: {{ $svc.service.containerPort }}
---
{{- if $svc.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ $name }}-hpa
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ $name }}
  minReplicas: {{ $svc.autoscaling.minReplicas }}
  maxReplicas: {{ $svc.autoscaling.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ $svc.autoscaling.targetCPU }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ $svc.autoscaling.targetMemory }}
{{- end }}